# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c6b7804caf33de623a5db97e4efba954fb5f58e1b67ebfe36af9d6d4af2dec80fc6472b22029cb9c1f4deebb9a3f09f98b4fdb0768e89bce10e9db0ba0f384c

test:
  secret_key_base: 62a50a9e270be6dafde06c197906bc579d93466cdc8b3200b02e8771f043b04f30ea4db949f6a010ff1c1090fb606c560516d8093819f5d7a3c2c8e98aeb35f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
